name: Build Hugo

on:
  schedule:
    # Run every day at 00.00 UTC+7
    - cron: '0 17 * * *'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          trust_level: 5
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: false

      - name: Build Hugo Binary
        run: |
          ./build
          git push origin master
