name: Pages Deployment

on:
  push:
    branches: master

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Page
        env:
          HUGO_OEMBED_ACCESSTOKEN: ${{ secrets.HUGO_OEMBED_ACCESSTOKEN }}
          HUGO_VSSUE_CLIENTSECRET: ${{ secrets.HUGO_VSSUE_CLIENTSECRET }}
        run: |
            npm ci
            npm run deploy

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./docs
          log_level: INFO
          css: true

      - name: Run ShellCheck
        if: |
          contains(github.event.head_commit.message, 'build:')
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './build'

      - name: Upload Docs
        if: |
          contains(github.event.head_commit.message, '[deploy]')
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'

  deploy:
    if: |
      contains(github.event.head_commit.message, '[deploy]')
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2