name: Pages Deployment

on:
  push:
    branches: main
  schedule:
    # Run every day at 00.00 UTC+7
    - cron: '0 17 * * *'

jobs:
  build:
    if: |
      github.event_name == 'schedule' || (github.event_name == 'push' && github.event.head_commit != null && !contains(github.event.head_commit.message, '[ci skip]'))
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          fetch-depth: 1

      - name: Run ShellCheck
        if: |
          github.event_name == 'push' && github.event.head_commit != null && contains(github.event.head_commit.message, 'build:')
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './build'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Hugo Binary (schedule)
        id: build-hugo
        if: github.event_name == 'schedule'
        run: |
          ./build --check

      - name: Build Hugo Binary (push)
        if: github.event_name == 'push' && (github.event.head_commit == null || !contains(github.event.head_commit.message, 'build:'))
        run: |
          ./build

      - name: Build Page
        if: |
          (github.event_name == 'schedule' || (github.event_name == 'push' && (github.event.head_commit == null || !contains(github.event.head_commit.message, 'build:'))))
          && steps.build-hugo.outputs.canceled != 'true'
        env:
          HUGO_OEMBED_ACCESSTOKEN: ${{ secrets.HUGO_OEMBED_ACCESSTOKEN }}
          HUGO_VSSUE_CLIENTSECRET: ${{ secrets.HUGO_VSSUE_CLIENTSECRET }}
        run: |
            npm ci
            npm run deploy

      - name: Validate HTML
        if: |
          (github.event_name == 'schedule' || (github.event_name == 'push' && (github.event.head_commit == null || !contains(github.event.head_commit.message, 'build:'))))
          && steps.build-hugo.outputs.canceled != 'true'
        run: |
            node validate.js

      - name: Upload Docs
        if: |
          github.event_name == 'schedule' || (github.event_name == 'push' && github.event.head_commit != null && contains(github.event.head_commit.message, '[deploy]'))
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  deploy:
    if: |
      github.event_name == 'schedule' || (github.event_name == 'push' && github.event.head_commit != null && contains(github.event.head_commit.message, '[deploy]'))
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
