name: HTML Validator

on:
  push:
    branches: master

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./
          log_level: INFO
          css: true
          blacklist: qga9x8k4gvvriy6on3ehsmm8bza2pg.html
