name: Page Test

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Page
        env:
          HUGO_OEMBED_ACCESSTOKEN: ${{ secrets.HUGO_OEMBED_ACCESSTOKEN }}
          HUGO_VSSUE_CLIENTSECRET: ${{ secrets.HUGO_VSSUE_CLIENTSECRET }}
        run: |
            npm install
            npm run buildtest

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./test
          log_level: INFO
          css: true
          blacklist: qga9x8k4gvvriy6on3ehsmm8bza2pg.html

#      - name: Lighthouse CI
#        uses: treosh/lighthouse-ci-action@v7
#        with:
#          configPath: './lighthouserc.json'
#          uploadArtifacts: true
#          temporaryPublicStorage: true
